# Generated by Django 5.0 on 2024-12-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_photo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
