# Generated by Django 5.0 on 2024-12-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='free_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='hot_water',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='is_ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='is_non_ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='parking_area',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='swimming_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
    ]
